/*
    artifact generator: C:\Users\stfnb\AppData\Roaming\npm\node_modules\@wizzi\cli\node_modules\@wizzi\plugin.js\lib\artifacts\js\module\gen\main.js
    package: @wizzi/plugin.js@0.8.9
    primary source IttfDocument: C:\My\wizzi\stfnbssl\wizzi\packages\wizzi-mtree\.wizzi\lib\jswizzi\jsWizziContext.js.ittf
    utc time: Thu, 02 Jan 2025 09:17:36 GMT
*/
// generated by wizzi.plugin.js.artifacts.js.module.gen.main
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }
var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; desc = parent = undefined; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

/**
     Used both for mTree buildup and interpolation
     mTree builup
     . composedMTree
     - loadHistory
     . productionContext
     . scriptCoder
     - toCode()
     (script code)
     - map
     (line to node map)
*/
var assert = require('assert');
var util = require('util');
var f_dateUtil = require('./functions/dateUtil');
var f_verify = require('./functions/verify');
var f_underscore = require('./functions/underscore');
var errors = require('./errors');
var JsWizziEvalHelper = require('./jsWizziEvalHelper');
var ContextData = require('./contextData');
var defaultValues = {
    'TODO': false
 };
var knownCallables = {
    'console': console, 
    '_': f_underscore, 
    'Object': Object, 
    'Array': Array, 
    'String': String, 
    'Date': Date, 
    'Number': Number, 
    'Map': Map, 
    'Set': Set, 
    'Math': Math, 
    'RegExp': RegExp, 
    'JSON': JSON, 
    'path': require('path'), 
    'util': util, 
    'dateUtil': f_dateUtil, 
    'verify': f_verify, 
    'Infinity': Infinity, 
    'NaN': NaN
 };
var builtinFunctions = {
    'Array': Array, 
    'String': String, 
    'Date': Date, 
    'Number': Number, 
    'RegExp': RegExp, 
    'isFinite': isFinite, 
    'isNaN': isNaN, 
    'parseFloat': parseFloat, 
    'parseInt': parseInt, 
    'decodeURI': decodeURI, 
    'decodeURIComponent': decodeURIComponent, 
    'encodeURI': encodeURI, 
    'encodeURIComponent': encodeURIComponent
 };
var ittfStates = {
    nodeContext: 0, 
    brickEvalContext: 1, 
    globalContext: 2, 
    callContext: 3
 };
/**
     This is a fake to allow a script for interpolation
     to have a function. The scope and recursion management of the function is a fake too, obviously.
     Waiting for damage, in very rare circumstances.
     TODO implementing function expressions should resolve the problem
*/
var FakeLoadHistoryForInterpolation = (function () {
    function FakeLoadHistoryForInterpolation() {
        _classCallCheck(this, FakeLoadHistoryForInterpolation);
        this.contextData = new ContextData(ittfStates.brickEvalContext);
    }
    FakeLoadHistoryForInterpolation.prototype.setContextsFromMTreeBuildUpScriptAst = function(contexts) {
        this.contexts = contexts;
        this.contextData.setFunctionScopesFromAst(this.getMTreeBrickFunctionScopes('f0'))
    }
    FakeLoadHistoryForInterpolation.prototype.getMTreeBrickFunctionScopes = function(brickKey) {
        var mTreeBricks = this.contexts.mTreeBricks;
        if (!mTreeBricks[brickKey]) {
            return {
                    functions: {
                        
                     }
                 };
        }
        else {
            return mTreeBricks[brickKey];
        }
    }
    return FakeLoadHistoryForInterpolation;
})();

var JsWizziContext = (function () {
    function JsWizziContext(composedMTree, productionContext, scriptCoder) {
        _classCallCheck(this, JsWizziContext);
        this.isForInterpolation = false;
        
        // The JsWizziContext is used for the
        
        // buildup of an MTree.
        
        // Create the JsWizziEvalHelper
        if (composedMTree && productionContext) {
            this.composedMTree = composedMTree;
            this.loadHistory = composedMTree.loadHistory;
            this.productionContext = productionContext;
            this.scriptCoder = scriptCoder;
            this.evalHelper = new JsWizziEvalHelper(this, composedMTree, productionContext);
        }
        // The JsWizziContext is used for interpolations.
        else {
            this.isForInterpolation = true;
            this.loadHistory = new FakeLoadHistoryForInterpolation();
        }
        
        this.globalContext = new ContextData(ittfStates.globalContext);
        this.callContextStack = [];
        this.callContext = null;
        if (this.isForInterpolation == false) {
            this.nodeContext = new ContextData(ittfStates.nodeContext);
        }
        this.loadingCallArguments = false;
        
        this.exprPending = null;
        
        // The first getValue will be for the '$' variable
        this.ittf_state = ittfStates.globalContext;
        this.currentMTreeBrickKey = null;
        // brickEvalContext is retrieved from JsWizziEvalHelper
        // each ittf source document has its brickEvalContext
        this.brickEvalContext = null;
        
        
        // freeze to avoid override of $ variable.
        if (this.isForInterpolation == false) {
            this.globalContext.declare('$', this.evalHelper);
            this.globalContext.$freeze();
        }
        
        // set global defaults and allowed functions
        this.globalContext.setValues(defaultValues);
        this.globalContext.setValues(knownCallables);
        this.globalContext.setValues(builtinFunctions);
        
        this.runningNodeId = null;
        
        this.sourceStack = [];
        this.source = null;
        
        if (typeof window === 'undefined') {
            this.startTimer = process.hrtime();
        }
        else {
            this.startTimer = window.performance.now();
        }
        
    }
    // Called by JsWizziRunner.run after parsing the mTreeBuildUpScript
    JsWizziContext.prototype.setContextsFromMTreeBuildUpScriptAst = function(contextsFromAst) {
        this.loadHistory.setContextsFromMTreeBuildUpScriptAst(contextsFromAst)
    }
    JsWizziContext.prototype.push = function() {
        // Called by JsWizziRunner.FunctionDeclarationCall
        // loog 'JsWizziContext: push'
        if (this.callContext) {
            this.callContextStack.push(this.callContext);
        }
        this.callContext = new ContextData(ittfStates.callContext);
        return this;
    }
    JsWizziContext.prototype.pop = function() {
        // Called by JsWizziRunner.FunctionDeclarationCall
        // loog 'JsWizziContext: pop'
        if (this.callContextStack.length > 0) {
            this.callContext = this.callContextStack.pop();
        }
        else {
            this.callContext = null;
        }
        return this;
    }
    JsWizziContext.prototype.clear = function() {
        this.globalContext.clear();
        if (this.isForInterpolation == false) {
            this.nodeContext.clear();
            if (this.brickEvalContext) {
                this.brickEvalContext.clear();
            }
            this.globalContext.declare('$', this.evalHelper);
            this.globalContext.$freeze();
        }
        this.globalContext.setValues(defaultValues);
        this.globalContext.setValues(knownCallables);
    }
    JsWizziContext.prototype.pushSource = function(source) {
        if (this.source) {
            this.sourceStack.push(this.source);
        }
        this.source = source;
    }
    JsWizziContext.prototype.popSource = function() {
        if (this.sourceStack.length > 0) {
            this.source = this.sourceStack.pop();
        }
        else {
            this.source = null;
        }
    }
    JsWizziContext.prototype.setRunningNodeId = function(id) {
        this.runningNodeId = id;
    }
    JsWizziContext.prototype.get_currentMTreeBrickInfo = function() {
        if (this.currentMTreeBrickKey == null) {
            return {
                    currentModel_uri: 'unavailable', 
                    currentModel_mixerUri: 'unavailable'
                 };
        }
        else {
            var mTreeBrickData = this.loadHistory.getMTreeBrickData(this.currentMTreeBrickKey);
            var mixerUri = null;
            if (mTreeBrickData.mTreeBrick.$mixerBrickKey) {
                var mixerMTreeBrickData = this.loadHistory.getMTreeBrickData(mTreeBrickData.mTreeBrick.$mixerBrickKey);
                mixerUri = mixerMTreeBrickData ? mixerMTreeBrickData.ittfDocumentUri : 'root model';
            }
            return {
                    currentModel_uri: mTreeBrickData.ittfDocumentUri, 
                    currentModel_mixerUri: mixerUri
                 };
        }
    }
    JsWizziContext.prototype.getIsCompileGlobals = function() {
        var ret = {
            '_': true, 
            'path': true, 
            'util': true, 
            'dateUtil': true, 
            'verify': true
         };
        var i, i_items=Object.keys(this.getGlobalValues()), i_len=Object.keys(this.getGlobalValues()).length, k;
        for (i=0; i<i_len; i++) {
            k = Object.keys(this.getGlobalValues())[i];
            if (!(defaultValues[k] || knownCallables[k] || builtinFunctions[k]) && k !== '$' && k !== 'NaN') {
                ret[k] = true;
            }
        }
        return ret;
    }
    JsWizziContext.prototype.elapsedTime = function(note) {
        var precision = 3;
        // divide by a million to get nano to milli
        if (typeof window === 'undefined') {
            var elapsed = process.hrtime(this.startTimer)[1] / 1000000;
            console.log(process.hrtime(this.startTimer)[0] + " s, " + elapsed.toFixed(precision) + " ms - " + note, __filename);
            this.startTimer = process.hrtime();
        }
        else {
            var elapsed = window.performance.now(this.startTimer)[1] / 1000000;
            console.log(window.performance.now(this.startTimer)[0] + " s, " + elapsed.toFixed(precision) + " ms - " + note, __filename);
            this.startTimer = window.performance.now();
        }
    }
    JsWizziContext.prototype.beginLoadingCallArguments = function() {
        this.loadingCallArguments = true;
    }
    JsWizziContext.prototype.endLoadingCallArguments = function() {
        this.loadingCallArguments = false;
    }
    JsWizziContext.prototype.declare = function(name, value) {
        // Runner: VariableDeclarator
        if (value && value.__is_function) {
            this.declareFunction(name, value)
        }
        else {
            if (this.ittf_state === ittfStates.globalContext) {
                this.globalContext.declare(name, value);
            }
            else if (this.ittf_state === ittfStates.nodeContext) {
                this.nodeContext.declare(name, value);
            }
            else {
                this.brickEvalContext.declare(name, value);
            }
        }
    }
    JsWizziContext.prototype.declareCallParam = function(name, value) {
        // called by Runner: FunctionDeclaration_Call
        // loog 'wizzi-mtree.jsWizziContext.declareCallParam', name, value
        this.callContext.declare(name, value);
    }
    JsWizziContext.prototype.undeclare = function(name) {
        if (this.ittf_state === ittfStates.globalContext) {
            this.globalContext.undeclare(name);
        }
        else if (this.ittf_state === ittfStates.nodeContext) {
            this.nodeContext.undeclare(name);
        }
        else {
            this.brickEvalContext.undeclare(name);
        }
    }
    JsWizziContext.prototype.isDeclared = function(name) {
        var ret = false;
        if (this.loadingCallArguments) {
            if (this.globalContext.isDeclared(name)) {
                return true;
            }
            if (this.callContext && this.callContext.isDeclared(name)) {
                return true;
            }
            if (this.isForInterpolation == false) {
                if (this.nodeContext.isDeclared(name)) {
                    return true;
                }
                if (this.brickEvalContext && this.brickEvalContext.isDeclared(name)) {
                    return true;
                }
                if (this.getFunction(name)) {
                    return true;
                }
            }
            return false;
        }
        else if (this.ittf_state === ittfStates.globalContext) {
            var ret = this.brickEvalContext ? this.brickEvalContext.isDeclared(name) : null;
            if (!ret) {
                ret = this.globalContext.isDeclared(name);
            }
        }
        else if (this.ittf_state === ittfStates.nodeContext) {
            var ret = this.nodeContext.isDeclared(name);
            if (!ret) {
                ret = this.globalContext.isDeclared(name);
            }
        }
        else {
            var ret = this.brickEvalContext.isDeclared(name);
            if (!ret) {
                ret = this.globalContext.isDeclared(name);
            }
            if (!ret) {
                ret = this.getFunction(name);
            }
        }
        if (!ret && this.callContext) {
            ret = this.callContext.isDeclared(name);
        }
        return ret;
    }
    JsWizziContext.prototype.setValue = function(name, value) {
        // it seems is called during interpolation only
        if (value && value.__is_function) {
            this.declareFunction(name, value)
        }
        else {
            if (this.ittf_state === ittfStates.globalContext) {
                this.globalContext.setValue(name, value);
            }
            else if (this.ittf_state === ittfStates.nodeContext) {
                this.nodeContext.setValue(name, value);
            }
            else {
                this.brickEvalContext.setValue(name, value);
            }
        }
    }
    JsWizziContext.prototype.setValues = function(values) {
        values = (values || {});
        for (var k in values) {
            this.setValue(k, values[k])
        }
    }
    JsWizziContext.prototype.put = function(name, value) {
        // Runner: Identifier_Set, UpdateExpression
        assert(this.ittf_state != ittfStates.nodeContext, 'put is an invalid operation for NodeContext state')
        if (value && value.__is_function) {
            this.declareFunction(name, value)
        }
        else {
            var ok = false;
            if (this.ittf_state === ittfStates.globalContext) {
                ok = this.globalContext.put(name, value);
            }
            else {
                ok = this.brickEvalContext.put(name, value);
                if (!ok) {
                    ok = this.globalContext.put(name, value);
                }
            }
            
            // loog 'wizzi-mtree.jsWizziContext.brickEvalContext.declaresStack', this.brickEvalContext.declaresStack
            
            // loog 'wizzi-mtree.jsWizziContext.brickEvalContext.valuesStack', this.brickEvalContext.valuesStack
            if (!ok) {
                throw new Error('jsWizziContext.put error. Not declared: ' + name);
            }
        }
    }
    JsWizziContext.prototype.getValue = function(name) {
        if (this.loadingCallArguments) {
            if (this.globalContext.isDeclared(name)) {
                return this.globalContext.getValue(name);
            }
            else if (this.callContext && this.callContext.isDeclared(name)) {
                return this.callContext.getValue(name);
            }
            else if (this.isForInterpolation == false) {
                if (this.nodeContext.isDeclared(name)) {
                    return this.nodeContext.getValue(name);
                }
                if (this.brickEvalContext && this.brickEvalContext.isDeclared(name)) {
                    return this.brickEvalContext.getValue(name);
                }
            }
            else {
                return undefined;
            }
        }
        else if (this.ittf_state === ittfStates.globalContext) {
            if (this.brickEvalContext && this.brickEvalContext.isDeclared(name)) {
                return this.brickEvalContext.getValue(name);
            }
            else if (this.globalContext.isDeclared(name)) {
                return this.globalContext.getValue(name);
            }
        }
        else if (this.ittf_state === ittfStates.nodeContext) {
            if (this.nodeContext.isDeclared(name)) {
                return this.nodeContext.getValue(name);
            }
            else if (this.globalContext.isDeclared(name)) {
                return this.globalContext.getValue(name);
            }
        }
        else {
            if (this.brickEvalContext.isDeclared(name)) {
                return this.brickEvalContext.getValue(name);
            }
            else if (this.globalContext.isDeclared(name)) {
                return this.globalContext.getValue(name);
            }
            else if (this.nodeContext.isDeclared(name)) {
                return this.nodeContext.getValue(name);
            }
        }
        if (this.callContext && this.callContext.isDeclared(name)) {
            return this.callContext.getValue(name);
        }
        else {
            var fn = this.getFunction(name);
            if (fn) {
                return fn;
            }
            // return undefined
            // loog 'JsWizziContext.getValue context value not found for', name
            // loog 'JsWizziContext.getValue ittf_state ', this.ittf_state
            // loog 'JsWizziContext.getValue currentMTreeBrickKey ', this.currentMTreeBrickKey
            // _ this.dumpValues
            else {
                throw new Error('jsWizziContext.getValue error. Not declared: ' + name);
            }
        }
    }
    JsWizziContext.prototype.getValues = function() {
        // TODO brickEvalContext needs globalValues ???
        if (this.ittf_state === ittfStates.globalContext) {
            return this.globalContext.getValues();
        }
        else if (this.ittf_state === ittfStates.nodeContext) {
            return this.nodeContext.getValues();
        }
        else {
            return this.brickEvalContext.getValues();
        }
    }
    JsWizziContext.prototype.setGlobalValues = function(values) {
        this.globalContext.setValues(values);
    }
    JsWizziContext.prototype.getGlobalValues = function() {
        return this.globalContext.getValues();
    }
    JsWizziContext.prototype.declareFunction = function(name, fn) {
        fn.__is_function = true;
        if (this.ittf_state === ittfStates.globalContext) {
            this.globalContext.declareFunction(name, fn);
        }
        else {
            this.brickEvalContext.declareFunction(name, fn);
        }
    }
    JsWizziContext.prototype.getFunction = function(name) {
        if (this.ittf_state === ittfStates.globalContext) {
            return this.globalContext.getFunction(name);
        }
        else {
            var ret = this.brickEvalContext.getFunction(name);
            return ret ? ret : this.globalContext.getFunction(name);
        }
    }
    JsWizziContext.prototype.beginExpr = function() {
        this.exprPending = {};
    }
    JsWizziContext.prototype.endExpr = function() {
        assert(this.exprPending, 'endExpr called without previous call to beginExpr')
        for (var k in this.exprPending) {
            this.put(k, this.exprPending[k])
        }
        this.exprPending = null;
    }
    JsWizziContext.prototype.abortExpr = function() {
        this.exprPending = null;
    }
    JsWizziContext.prototype.dumpValues = function() {
        // TODO if this.verbose
        console.log('Dump context value for debug');
        console.log('JsWizziContext ittf_state ', this.ittf_state);
        console.log('JsWizziContext currentMTreeBrickKey ', this.currentMTreeBrickKey);
        if (this.brickEvalContext) {
            console.log('Local values');
            this.brickEvalContext.dumpValues();
        }
        console.log('Global values');
        this.globalContext.dumpValues();
    }
    JsWizziContext.prototype.getDeclaredInfo = function() {
        var ret = [];
        if (this.ittf_state === ittfStates.globalContext) {
            ret.push('state=global')
            ret.push('global declares:' + this.globalContext.getDeclaredInfo())
        }
        else if (this.ittf_state === ittfStates.nodeContext) {
            ret.push('state=node')
        }
        else {
            ret.push('state=brick:' + this.currentMTreeBrickKey)
            ret.push('model declares:' + this.brickEvalContext.getDeclaredInfo())
            ret.push('global declares:' + this.globalContext.getDeclaredInfo())
        }
        return ret.join(', ');
    }
    /**
         The JsWizziRunner is entering a block of statements
         with instructions for the buildup
         of the final MTree.
    */
    JsWizziContext.prototype.set_NodeContext = function() {
        if (this.isForInterpolation) {
            return ;
        }
        
        // we already are in a nodeContext state
        if (this.ittf_state === ittfStates.nodeContext) {
            return ;
        }
        // loog '*** => set_NodeContext'
        this.ittf_state = ittfStates.nodeContext;
        this.currentMTreeBrickKey = null;
        this.brickEvalContext = null;
    }
    /**
         The JsWizziRunner is entering a block of global statements
         declared inside an ittf document.
         Example:
         001     $global var message = 'hello';
    */
    JsWizziContext.prototype.set_GlobalContext = function(brickKey) {
        // get_value has scope: global and the current MTreeBrickEvalContext
        // set_value puts value into global
        
        // added 7/8/17
        
        // Must stay before the call to getMTreeBrickEvalContext
        
        // to allow debug info about brickKey
        if (this.isForInterpolation == false && this.currentMTreeBrickKey !== brickKey) {
            this.currentMTreeBrickKey = brickKey;
            this.brickEvalContext = this.evalHelper.getMTreeBrickEvalContext(brickKey, -1);
            ;
            if (this.brickEvalContext && this.brickEvalContext.__is_error) {
                return this.brickEvalContext;
            }
            assert(this.brickEvalContext, 'set_MTreeBrickEvalContext brickEvalContext for key ' + brickKey + ' undefined');
        }
        
        // we already are in a globalContext state
        if (this.ittf_state === ittfStates.globalContext) {
            return ;
        }
        // loog '*** => set_GlobalContext'
        this.ittf_state = ittfStates.globalContext;
        // via 7/8/17 set this.currentMTreeBrickKey = null
        // via 7/8/17 set this.brickEvalContext = null
    }
    /**
         The JsWizziRunner is entering a block of statements or
         a node expression that are in the scope of an mTreeBrick.
         They could be statements declared in a mixed ittf
         document using the $ IttfCommand:
        
         001     $ var message = 'hello';
        
         or it could be a node expression that the JsWizziEvalHelper
         has to interpolate:
        
         001     function ${functionName}
        
    */
    JsWizziContext.prototype.set_MTreeBrickEvalContext = function(brickKey, line) {
        if (this.isForInterpolation) {
            return ;
        }
        this.ittf_state = ittfStates.brickEvalContext;
        if (this.currentMTreeBrickKey === brickKey) {
            return ;
        }
        // Must stay before the call to getMTreeBrickEvalContext
        // to allow debug info about brickKey
        this.currentMTreeBrickKey = brickKey;
        this.brickEvalContext = this.evalHelper.getMTreeBrickEvalContext(brickKey, line);
        ;
        if (this.brickEvalContext && this.brickEvalContext.__is_error) {
            return this.brickEvalContext;
        }
        assert(this.brickEvalContext, 'set_MTreeBrickEvalContext brickEvalContext for key ' + brickKey + ' undefined');
        // loog '*** => set_MTreeBrickEvalContext', brickKey
        return this.brickEvalContext;
    }
    JsWizziContext.prototype.get_currentMTreeBrickKey = function() {
        return this.currentMTreeBrickKey;
    }
    JsWizziContext.prototype.enterFunctionEvalContext = function(functionName) {
        // Called by Runner: runnerCall
        // if isForInterpolation then use instance of FakeLoadHistoryForInterpolation
        var evalContext = this.isForInterpolation ? this.loadHistory.contextData : this.brickEvalContext;
        var previousFunctionName = evalContext.enterFunction(functionName);
        return {
                brickKey: this.currentMTreeBrickKey, 
                functionName: previousFunctionName
             };
    }
    JsWizziContext.prototype.exitFunctionEvalContext = function(functionName, brickKey, restoreFunctionName) {
        // Called by Runner: runnerCall
        // set the previous functionName on brickKey
        if (this.isForInterpolation) {
            this.loadHistory.contextData.exitFunction(functionName, restoreFunctionName)
        }
        else {
            var brickEvalContext = this.evalHelper.getMTreeBrickEvalContext(brickKey);
            if (brickEvalContext && brickEvalContext.__is_error) {
                return brickEvalContext;
            }
            brickEvalContext.exitFunction(functionName, restoreFunctionName)
        }
    }
    JsWizziContext.prototype.getNodeFromScriptMap = function(line) {
        if (this.scriptCoder) {
            return this.scriptCoder.getNodeFromScriptMap(line);
        }
        else {
            return null;
        }
    }
    return JsWizziContext;
})();


JsWizziContext.createMockComposedMTree = function() {
    return {
            loadHistory: new FakeLoadHistoryForInterpolation()
         };
}
;

module.exports = JsWizziContext;