/*
    artifact generator: C:\My\wizzi\stfnbssl\wizzi.lastsafe.plugins\packages\wizzi.plugin.js\lib\artifacts\js\module\gen\main.js
    package: wizzi-js@
    primary source IttfDocument: C:\My\wizzi\stfnbssl\wizzi\packages\wizzi\.wizzi\lib\production\wzjobLoader.js.ittf
    utc time: Fri, 26 Apr 2024 16:45:47 GMT
*/
'use strict';
// generated by wizzi.plugin.js.artifacts.js.module.gen.main
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }
var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; desc = parent = undefined; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

var verify = require('@wizzi/utils').verify;
var path = require('path');
var util = require('util');
var assert = require('assert');
var async = require('async');
var verify = require('@wizzi/utils').verify;
/**
     Async load a 'wzjob' wizzi model and accumulate
     artifactInfoConfig elements.
     If the 'wzjob' model contains "artifact" elements
     check that they have not already been added and add them to
     the artifactInfoConfigs collection.
     If the 'wzjob' model contains 'artifact' elements with the
     "isWzJob" attribute check that they have not already been processed
     and add them to pendingWzJobRequests.
*/
var WzJobLoader = (function () {
    function WzJobLoader(productionManager) {
        _classCallCheck(this, WzJobLoader);
        this.productionManager = productionManager;
        this.globalModelInfoConfigs = [];
        this.pendingWzJobRequests = [];
        // FIXME checking pendingWzJobRequests should be enough. Why seenWzJobRequests?
        this.seenWzJobRequests = [];
        this.artifactInfoConfigs = [];
    }
    WzJobLoader.prototype.load = function(wzjobRequest, callback) {
        this.seenWzJobRequests.push(wzjobRequest);
        var ittfDocumentUri = verify.isAbsolutePath(wzjobRequest.model.src) ? wzjobRequest.model.src : path.join(wzjobRequest.model.cwd, wzjobRequest.model.src);
        // wzjobRequest.context has not been implemented yet
        // and probably it will never be.
        // Its properties should be produced by previous
        // executions in the wzjob load recursive process.
        // To pass a context to the wzjob mTree loader
        // we use the globalContext of the wizziFactory.
        var that = this;
        this.productionManager.loadWzJob(ittfDocumentUri, wzjobRequest.context || {}, function(err, wzjobModel) {
            if (err) {
                return callback(err);
            }
            that.processWzJobModel(wzjobModel);
            return callback(null, that);
        })
    }
    WzJobLoader.prototype.addGlobalModelInfoConfig = function(globalModelInfoConfig) {
        if (this._isGlobalModelInfoConfigAdded(globalModelInfoConfig) == false) {
            this.globalModelInfoConfigs.push(globalModelInfoConfig);
        }
    }
    WzJobLoader.prototype._isGlobalModelInfoConfigAdded = function(globalModelInfoConfig) {
        var i, i_items=this.globalModelInfoConfigs, i_len=this.globalModelInfoConfigs.length, item;
        for (i=0; i<i_len; i++) {
            item = this.globalModelInfoConfigs[i];
            if (this._areGlobalModelInfoConfigsEqual(item, globalModelInfoConfig)) {
                return true;
            }
        }
        return false;
    }
    WzJobLoader.prototype.addPendingWzJobRequest = function(artifactInfoConfig) {
        if (this._isWzJobSeen(artifactInfoConfig) == false) {
            this.pendingWzJobRequests.push(artifactInfoConfig);
        }
    }
    WzJobLoader.prototype._isWzJobSeen = function(artifactInfoConfig) {
        var i, i_items=this.seenWzJobRequests, i_len=this.seenWzJobRequests.length, item;
        for (i=0; i<i_len; i++) {
            item = this.seenWzJobRequests[i];
            if (this._areWzJobRequestsEqual(item, artifactInfoConfig)) {
                return true;
            }
        }
        return false;
    }
    WzJobLoader.prototype.addArtifactInfoConfig = function(artifactInfoConfig) {
        if (this._isArtifactInfoConfigAdded(artifactInfoConfig) == false) {
            this.artifactInfoConfigs.push(artifactInfoConfig);
        }
    }
    WzJobLoader.prototype._isArtifactInfoConfigAdded = function(artifactInfoConfig) {
        var i, i_items=this.artifactInfoConfigs, i_len=this.artifactInfoConfigs.length, item;
        for (i=0; i<i_len; i++) {
            item = this.artifactInfoConfigs[i];
            if (this._areArtifactInfoConfigsEqual(item, artifactInfoConfig)) {
                return true;
            }
        }
        return false;
    }
    WzJobLoader.prototype._areGlobalModelInfoConfigsEqual = function(a, b) {
        return a.exportName === b.exportName && a.src === b.src;
    }
    WzJobLoader.prototype._areWzJobRequestsEqual = function(a, b) {
        return a.model.cwd === b.model.cwd && a.model.src === b.model.src;
    }
    WzJobLoader.prototype._areArtifactInfoConfigsEqual = function(a, b) {
        return a.model.cwd === b.model.cwd && a.model.src === b.model.src && a.dest.baseFolder === b.dest.baseFolder && a.dest.folder === b.dest.folder && a.dest.path === b.dest.path && a.dest.extension === b.dest.extension && a.gen.generator === b.gen.generator;
    }
    WzJobLoader.prototype.processWzJobModel = function(wzjobModel) {
        /**
             Analizes a wizzi model of schema `wzjob`.
             Creates a wizzi.productionManager.artifactInfoConfig object for each artifact production request.
             Accumulates the requests calling the methods:
             . addPendingWzJobRequest(artifactInfoConfig)
             . addArtifactInfoConfig(artifactInfoConfig)
            
             There are four types of artifacts
             .1 Wizzi Model artifact
             .2 Wizzi Model collection artifact
             .3 Code write artifact
             .4 WzJob artifact
             Production structure
             { wzjob
             [ productions
             { production
             string destFolder
             [ lines
             { line
             string cwdFolder
             string destFolder
             [ artifacts
             { artifact
             string src
             The path to the primary source document of the artifact.
             If relative, the base path is the "cwdFolder" of the parent line.
             If the artifact is a code write artifact the "src" attribute must not be declared.
             string destPath
             The artifact source file path "src" is the default relative destination path
             of the generated artifact. When set, this attribute overrides the default.
             It may be an absolute path.
             If the artifact is a code write generation the "destPath" attribute must be declared.
        */
        var artifactInfoConfig;
        var i, i_items=wzjobModel.models, i_len=wzjobModel.models.length, wzjobModelElement;
        for (i=0; i<i_len; i++) {
            wzjobModelElement = wzjobModel.models[i];
            if (verify.isNotEmpty(wzjobModelElement.exportName)) {
                var globalModelInfoConfig = {
                    exportName: wzjobModelElement.exportName, 
                    src: wzjobModelElement.src, 
                    cwd: wzjobModel.modelsBaseFolder, 
                    schema: wzjobModelElement.schema, 
                    format: wzjobModelElement.format
                 };
                this.addGlobalModelInfoConfig(globalModelInfoConfig);
            }
        }
        var i, i_items=wzjobModel.productions, i_len=wzjobModel.productions.length, wzjobProductionElement;
        for (i=0; i<i_len; i++) {
            wzjobProductionElement = wzjobModel.productions[i];
            // loog 'wizzi.wzjobLoader.processWzJobModel.production', wzjobProductionElement.wzName, util.inspect(wzjobProductionElement, { depth: 2 })
            var j, j_items=wzjobProductionElement.lines, j_len=wzjobProductionElement.lines.length, wzjobLineElement;
            for (j=0; j<j_len; j++) {
                wzjobLineElement = wzjobProductionElement.lines[j];
                // loog 'wizzi.wzjobLoader.processWzJobModel.line', wzjobLineElement.wzName, util.inspect(wzjobLineElement, { depth: null })
                var k, k_items=wzjobLineElement.artifacts, k_len=wzjobLineElement.artifacts.length, wzjobArtifactElement;
                for (k=0; k<k_len; k++) {
                    wzjobArtifactElement = wzjobLineElement.artifacts[k];
                    // loog 'wizzi.wzjobLoader.processWzJobModel.artifact', util.inspect(wzjobArtifactElement, { depth: 1 })
                    
                    /**
                        * THIS IS A CODEWRITE artifact
                        * this artifact is generated by a code write generation
                    */
                    if (verify.isEmpty(wzjobArtifactElement.src)) {
                        artifactInfoConfig = {
                            name: wzjobArtifactElement.wzName, 
                            options: {}, 
                            contexts: [], 
                            gen: {
                                generator: wzjobArtifactElement.generator
                             }, 
                            dest: {
                                baseFolder: wzjobModel.destBaseFolder, 
                                folder: wzjobLineElement.destFolder || wzjobProductionElement.destFolder, 
                                path: wzjobArtifactElement.destPath, 
                                extension: wzjobArtifactElement.extension
                             }, 
                            collection: wzjobArtifactElement.collection, 
                            toString: function() {
                                return 'Artifact info config: ' + this.name + '/' + this.gen.generator;
                            }
                         };
                        var l, l_items=wzjobArtifactElement.modelRefs, l_len=wzjobArtifactElement.modelRefs.length, modelRef;
                        for (l=0; l<l_len; l++) {
                            modelRef = wzjobArtifactElement.modelRefs[l];
                            // loog 'WizziJob.getArtifactInfoConfigs.modelRef', modelRef.wzName, modelRef.collName, modelRef.modelCollections.length, util.inspect(modelRef, { depth: 2 })
                            var modelInfoConfig = this._createContextModelInfoConfig(wzjobModel, modelRef);
                            artifactInfoConfig.contexts.push(modelInfoConfig);
                        }
                    }
                    // This is a WIZZIMODEL artifact or WFJOB artifact
                    // loog 'WizziJob.getArtifactInfoConfigs.art', wzjobArtifactElement.wzName, wzjobLineElement.srcFolder, wzjobArtifactElement.src, wzjobArtifactElement.schema
                    else {
                        artifactInfoConfig = {
                            name: wzjobArtifactElement.wzName, 
                            options: {}, 
                            model: {
                                cwd: wzjobLineElement.cwdFolder, 
                                src: wzjobArtifactElement.src, 
                                ignore: wzjobArtifactElement.ignore, 
                                schema: wzjobArtifactElement.schema, 
                                format: wzjobArtifactElement.format, 
                                isCompile: wzjobArtifactElement.isCompile, 
                                contexts: [], 
                                transformers: this._getTransformerList(wzjobArtifactElement.transformers)
                             }, 
                            isWzJob: wzjobArtifactElement.isWzJob, 
                            isWzModelType: wzjobArtifactElement.isWzModelType, 
                            gen: {
                                generator: wzjobArtifactElement.generator
                             }, 
                            dest: {
                                baseFolder: wzjobModel.destBaseFolder, 
                                folder: wzjobLineElement.destFolder || wzjobProductionElement.destFolder, 
                                path: wzjobArtifactElement.destPath, 
                                extension: wzjobArtifactElement.extension
                             }, 
                            collection: wzjobArtifactElement.collection, 
                            toString: function() {
                                return 'Artifact info config: ' + this.name + '/' + this.model.src + '/' + this.model.schema;
                            }
                         };
                        var l, l_items=wzjobArtifactElement.modelRefs, l_len=wzjobArtifactElement.modelRefs.length, modelRef;
                        for (l=0; l<l_len; l++) {
                            modelRef = wzjobArtifactElement.modelRefs[l];
                            // loog 'WizziJob.getArtifactInfoConfigs.modelRef', modelRef.wzName, modelRef.collName, modelRef.modelCollections.length, util.inspect(modelRef, { depth: 2 })
                            var modelInfoConfig = this._createContextModelInfoConfig(wzjobModel, modelRef);
                            artifactInfoConfig.model.contexts.push(modelInfoConfig);
                        }
                    }
                    // loog 'WizziJob.artifactInfoConfig', util.inspect(artifactInfoConfig, { depth: 1 })
                    if (wzjobArtifactElement.isWzJob) {
                        this.addPendingWzJobRequest(artifactInfoConfig);
                    }
                    else {
                        this.addArtifactInfoConfig(artifactInfoConfig);
                    }
                }
            }
        }
    }
    /**
         params
         { wzjobModelRefElement
         string wzName
         is the key for the wzjobModelElement
         string collName
         string collItemName
         [ collPathTemplateValues
         { collPathTemplateValue
    */
    WzJobLoader.prototype._createContextModelInfoConfig = function(wzjobModel, wzjobModelRefElement) {
        // model existence has already been verified loading the wzjobModel
        var wzjobModelElement = wzjobModel.getModel(wzjobModelRefElement.wzName);
        var modelInfoConfig = {
            exportName: wzjobModelRefElement.exportName, 
            src: this._getModelSrc(wzjobModel, wzjobModelElement.src, wzjobModelElement), 
            schema: wzjobModelElement.schema, 
            format: wzjobModelElement.format, 
            isCompile: wzjobModelElement.isCompile, 
            contexts: [], 
            transformers: this._getTransformerList(wzjobModelRefElement.transformers), 
            coll: null
         };
        
        // Single items of a collection contained in a WizziModelInstance may act as data contexts
        
        // of artifacts where each collection item generates a separate artifact.
        
        // The coll property specifies:
        
        // . name                the collection name
        
        // . itemName            the export name of the collection item when acting as a data context
        
        // . pathTemplateValues  the property names of the collection item that will be used to build
        
        // the destination path of the artifact
        if (wzjobModelRefElement.collName) {
            modelInfoConfig.coll = {
                name: wzjobModelRefElement.collName, 
                itemName: wzjobModelRefElement.collItemName, 
                pathTemplateValues: wzjobModelRefElement.collPathTemplateValues
             };
        }
        // recurse creation of context modelInfos
        var i, i_items=wzjobModelElement.modelRefs, i_len=wzjobModelElement.modelRefs.length, modelRef;
        for (i=0; i<i_len; i++) {
            modelRef = wzjobModelElement.modelRefs[i];
            modelInfoConfig.contexts.push(this._createContextModelInfoConfig(wzjobModel, modelRef))
        }
        return modelInfoConfig;
    }
    WzJobLoader.prototype._getArtifactModelSrc = function(cwd, src, node) {
        /**
             When 'src' is relative, the base path is the 'cwd' attribute
             declared on the wzjobLine element.
        */
        if (verify.isAbsolutePath(src)) {
            return src;
        }
        else {
            if (verify.isString(cwd)) {
                return path.join(cwd, src);
            }
            else {
                return errorMsg('PathError', "The src attribute of the artifact element: " + src + ' is a relative path. A cwd attribute is required on the line element.', node);
            }
        }
    }
    WzJobLoader.prototype._getModelSrc = function(wzjobModel, src, node) {
        /**
             When 'src' is relative, the base path is the 'modelsBaseFolder'
             declared on the 'wzjob' element.
        */
        if (verify.isAbsolutePath(src)) {
            return src;
        }
        else {
            if (verify.isString(wzjobModel.modelsBaseFolder)) {
                return path.join(wzjobModel.modelsBaseFolder, src);
            }
            else {
                return errorMsg('PathError', "The src attribute of the model element: " + src + ' is a relative path. A models-base-folder attribute is required on the wzjob element.', node);
            }
        }
    }
    WzJobLoader.prototype._getTransformerList = function(transformers) {
        var ret = [];
        var i, i_items=transformers, i_len=transformers.length, item;
        for (i=0; i<i_len; i++) {
            item = transformers[i];
            ret.push({
                name: item.wzName, 
                dumpFile: item.dumpFile
             })
        }
        return ret;
    }
    return WzJobLoader;
})();

/**
     A 'wzjob' model may contain the request for the execution
     of another wzjob. The accumulation of all the requested artifacts
     must be a recursive action.
    
     The same wizzi.production.WzJobLoader instance is passed through
     the recursive loadings.
     It loads the `wzjob` requests and checks that wzjobs and
     wzjobArtifactModels are processed once.
     (see methods _areWzJobRequestsEqual and _areArtifactInfoConfigsEqual for equality criteria)
    
     At the end of the recursion the WzJobLoader instance contains
     the wizzi.artifact.artifactInfo instances that have to be
     executed by the wizzi.production.productionManager.
    
*/
function AsyncRecurseWzJobLoad(wzjobRequest, callback) {
    if (typeof(callback) !== 'function') {
        throw new Error(
            error('InvalidArgument', 'AsyncRecurseWzJobLoad', 'The callback parameter must be a function. Received: ' + callback)
        );
    };
    if (verify.isObject(wzjobRequest) === false) {
        return callback(error(
            'InvalidArgument', 'AsyncRecurseWzJobLoad', { parameter: 'wzjobRequest', message: 'The wzjobRequest parameter must be an object. Received: ' + wzjobRequest }
        ));
    }
    if (verify.isObject(wzjobRequest.wzjobLoader) === false) {
        return callback(error(
            'InvalidArgument', 'AsyncRecurseWzJobLoad', { parameter: 'wzjobRequest.wzjobLoader', message: 'The wzjobRequest.wzjobLoader parameter must be an object. Received: ' + wzjobRequest.wzjobLoader }
        ));
    }
    console.log('=');
    console.log('= ========= wizzi.AsyncRecurseWzJobLoad. Start. wzjobRequest.model : ', wzjobRequest.model);
    console.log('=');
    var wzjobLoader = wzjobRequest.wzjobLoader;
    wzjobLoader.load(wzjobRequest, function(err, result) {
        if (err) {
            return callback(err);
        }
        console.log('=');
        console.log('= ========= wizzi.AsyncRecurseWzJobLoad. Results. ', 'seenWzJobRequests: ', result.seenWzJobRequests.length, ', globalModelInfoConfigs: ', result.globalModelInfoConfigs.length, ', artifactInfoConfigs: ', result.artifactInfoConfigs.length, ', pendingWzJobRequests: ', result.pendingWzJobRequests);
        console.log('=');
        
        // set the same wzjobLoader for any jobRequest
        
        // recurse
        if (result.pendingWzJobRequests.length > 0) {
            var jobRequests = result.pendingWzJobRequests;
            result.pendingWzJobRequests = [];
            var i, i_items=jobRequests, i_len=jobRequests.length, item;
            for (i=0; i<i_len; i++) {
                item = jobRequests[i];
                item.wzjobLoader = wzjobLoader;
            }
            async.map(jobRequests, AsyncRecurseWzJobLoad, function(err, result) {
                if (err) {
                    return callback(err);
                }
                return callback(null, wzjobLoader);
            })
        }
        else {
            return callback(null, wzjobLoader);
        }
    })
}
function errorMsg(code, message, node) {
    message = node ? new errors.NodeError(message, node).toString() : message;
    return {
            __is_error: true, 
            code: code, 
            message: message
         };
}

module.exports = {
    WzJobLoader: WzJobLoader,
    AsyncRecurseWzJobLoad: AsyncRecurseWzJobLoad
};
/**
  params
    string code
      # the error name or number
    string method
    string message
      # optional
    { innerError
      # optional
*/
function error(code, method, message, innerError) {
    var parameter = null;
    if (verify.isObject(message)) {
        parameter = message.parameter;
        message = message.message;
    }
    return verify.error(innerError, {
        name: ( verify.isNumber(code) ? 'Err-' + code : code ),
        method: '.' + method,
        parameter: parameter,
        sourcePath: __filename
    }, message || 'Error message unavailable');
}
